Выбор файла загрузки

In [1]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

Считывание датасета из файла train.csv

In [2]:
import pandas as pd
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Вывод основной информации о датасете: информация о типах данных, числе пропусков, средних значения и т.д.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Процент выживаемости у каждого класса пассажиров (Pclass)

In [6]:
for i in range(3):
  print(f'Выживаемость пассажиров {i+1} класса: {round(df.groupby('Pclass')['Survived'].sum()[i+1] / df['Survived'].count() * 100, 2)}%')

Выживаемость пассажиров 1 класса: 15.26%
Выживаемость пассажиров 2 класса: 9.76%
Выживаемость пассажиров 3 класса: 13.36%

Вывод самого популярного мужского и самого популярного женского имени на корабле

In [7]:
def first_name_male(name):
    first = name.str.extract(r'Mr\.\s+(\w+)', expand=False)
    first.loc[first.isna()] = name.str.extract(r'\.\s+(\w+)', expand=False)
    return first
male_names = first_name_male(df.loc[df['Sex']=='male','Name'])
print(f'Самое популярное мужское имя {male_names.value_counts().index[0]} встречается {male_names.value_counts().iloc[0]} раз')
def first_name_female(name):
    first = name.str.extract(r"Mrs\.\s+[^(]*\((\w+)", expand=False)
    first.loc[first.isna()] = name.str.extract(r"\.\s+(\w+)", expand=False)
    return first
female_names = first_name_female(df.loc[df['Sex']=='female','Name'])
print(f'Самое популярное женское имя {female_names.value_counts().index[0]} встречается {female_names.value_counts().iloc[0]} раз')

Самое популярное мужское имя William встречается 35 раз
Самое популярное женское имя Anna встречается 15 раз

Вывод самого популярного мужского и самого популярного женского имени на корабле в каждом классе

In [8]:
df = pd.read_csv('train.csv')
df['Name'] = df['Name'].apply(lambda x: x[x.find('.')+2:])
df['Name'] = df['Name'].apply(lambda x: x[x.find('(')+1:])
df['Name'] = df['Name'].apply(lambda x : x if x.find(' ') == -1 else x[:x.find(' ')])
df.groupby("Pclass")["Name"].value_counts()

for i in range(3):
  print(f"Самое популярное мужское имя {i+1} класса - {df[(df['Sex'] == 'male') & (df['Pclass'] == i+1)]['Name'].value_counts().index[0]} - встречается {df[(df['Sex'] == 'male') & (df['Pclass'] == i+1)]['Name'].value_counts().iloc[0]} раз")
  print(f"Самое популярное женское имя {i+1} класса - {df[(df['Sex'] == 'female') & (df['Pclass'] == i+1)]['Name'].value_counts().index[0]} - встречается {df[(df['Sex'] == 'female') & (df['Pclass'] == i+1)]['Name'].value_counts().iloc[0]} раз")

Самое популярное мужское имя 1 класса - William - встречается 11 раз
Самое популярное женское имя 1 класса - Elizabeth - встречается 5 раз
Самое популярное мужское имя 2 класса - William - встречается 9 раз
Самое популярное женское имя 2 класса - Elizabeth - встречается 5 раз
Самое популярное мужское имя 3 класса - William - встречается 15 раз
Самое популярное женское имя 3 класса - Anna - встречается 9 раз

Вывод части таблицы с пассажирами, возраст которых больше 44 лет

In [9]:
df[df['Age'] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,Timothy,male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,Elizabeth,female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,Mary,female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,Edward,male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,53,1,1,Myna,female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,Peter,male,51.0,0,0,113055,26.5500,E17,S
862,863,1,1,Margaret,female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,Sallie,female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,Victor,male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,Lily,female,56.0,0,1,11767,83.1583,C50,C

Вывод части таблицы с пассажирами мужского пола, возраст которых меньше 44 лет

In [10]:
df.loc[df['Sex']=='male'].loc[df['Age'] < 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Owen,male,22.0,1,0,A/5 21171,7.250,NaN,S
4,5,0,3,William,male,35.0,0,0,373450,8.050,NaN,S
7,8,0,3,Gosta,male,2.0,3,1,349909,21.075,NaN,S
12,13,0,3,William,male,20.0,0,0,A/5. 2151,8.050,NaN,S
13,14,0,3,Anders,male,39.0,1,5,347082,31.275,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,Frederick,male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,S
884,885,0,3,Henry,male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S
886,887,0,2,Juozas,male,27.0,0,0,211536,13.000,NaN,S
889,890,1,1,Karl,male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,Patrick,male,32.0,0,0,370376,7.750,NaN,Q

Вывод количества n-местных кабин (в которых было 2, 3, 4, ... человека)

In [11]:
import numpy as np
a = df.groupby('Cabin')['PassengerId'].count().values
unique, counts = np.unique(a, return_counts=True)

for i, j in zip(unique, counts):
  print(f'{i}-местных кабин: {j} шт.')

1-местных кабин: 101 шт.
2-местных кабин: 38 шт.
3-местных кабин: 5 шт.
4-местных кабин: 3 шт.